name: Test Project
on: [push, workflow_dispatch]
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: 
    - name : Get code
      uses: actions/checkout@v4
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with:
       node-version: 20
    - name: Install dependencies
      run: npm ci
      working-directory: Code/02 Basics/03 Finished Project
    - name: Run Test
      run: npm test
      working-directory: Code/02 Basics/03 Finished Project
  deploy:
    runs-on: ubuntu-latest
    needs: test-job
    steps: 
    - name : Get code
      uses: actions/checkout@v4
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with:
       node-version: 20
    - name: Install dependencies
      run: npm ci
      working-directory: Code/02 Basics/03 Finished Project
    - name: Build project
      run: npm build
      working-directory: Code/02 Basics/03 Finished Project
    - name: Deploy code
      run: echo "Deploying..."
